### ISSUE TITLE
How do you track humans?

### ISSUE THREAD

**Issue by FernandezR** [aijunbai/pfs#1]
Hello,
I read your paper on Intention-Aware Multi-Human Tracking and would like to try to implement a similar algorithm on the robots in the UT Austin BWI Lab. Could you tell me how you were tracking humans, are you tracking joint movements or something else?

Thanks,
Rolando

**Comment by aijunbai** [comment]
Hi,
A human detector is necessary to provide detection results for the algorithm. It is supposed to be able to output the positions of detected humans.

**Comment by FernandezR** [comment]
Yes, we have a human detector in our package, but what I'm more interested is in how you were determining whether a person was going to move or stay in roughly the same place?

**Comment by aijunbai** [comment]
The basic idea is for humans with different intentions, we have different motion models, so the particle filter will be able to identify the true intentions of humans after several cycles of updating.

**Comment by FernandezR** [comment]
Also could you tell what camera device were you using, was it a kinect or a kinect2 ?

**Comment by aijunbai** [comment]
I think it was a kinect2.
